# Generated by Django 2.2.4 on 2019-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
