# Generated by Django 2.2.4 on 2019-08-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20190827_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
